ATRIBUTOS = {
    'tribunal': 'Identificação do Tribunal pela sigla',
    'numeroProcesso': 'Numeração Única (CNJ) do processo sem formatação',
    'dataAjuizamento': 'Data de ajuizamento da capa do processo',
    'grau': 'Identificação da instância/grau (G1, G2, JE, etc...)',
    'nivelSigilo': 'Nível de sigilo',
    'formato': 'Identificação de processo Físico ou Eletrônico',
    'formato.codigo': 'Código de identificação do formato do processo',
    'formato.nome': 'Identificação se é Físico ou Eletrônico',
    'sistema': 'Sistema processual de origem do processo no Tribunal',
    'sistema.codigo': 'Código do sistema processual',
    'sistema.nome': 'Descrição do sistema processual',
    'classe': 'Classe Processual conforme TPU',
    'classe.codigo': 'Código da classe processual',
    'classe.nome': 'Descrição da classe processual',
    'assuntos': 'Assuntos do Processo conforme TPU',
    'assuntos.codigo': 'Código do assunto',
    'assuntos.nome': 'Descrição do assunto',
    'orgaoJulgador': 'Órgão Julgador',
    'orgaoJulgador.codigo': 'Código da serventia/vara atual do processo',
    'orgaoJulgador.nome': 'Nome da serventia/vara',
    'orgaoJulgador.codigoMunicipioIBGE': 'Identificação do município pelo código do IBGE',
    'movimentos': 'Movimentos Processuais',
    'movimentos.codigo': 'Código da movimentação processual conforme TPU',
    'movimentos.nome': 'Descrição da movimentação',
    'movimentos.dataHora': 'Data e hora da ocorrência de movimentação',
    'movimentos.complementosTabelados': 'Lista de complementos tabelados daquela movimentação',
    'movimentos.complementosTabelados.codigo': 'Código da variável de movimento tabelado',
    'movimentos.complementosTabelados.descricao': 'Descrição da variável do movimento tabelado',
    'movimentos.complementosTabelados.valor': 'Código do complemento tabelado',
    'movimentos.complementosTabelados.nome': 'Descrição do complemento tabelado',
    'movimentos.orgaoJulgador': 'Órgão julgador do movimento',
    'movimentos.orgaoJulgador.codigoOrgao': 'Código da serventia/vara do movimento',
    'movimentos.orgaoJulgador.nomeOrgao': 'Nome da serventia/vara',
}