ENDPOINTS_TSU = {
    'TST': '/api_publica_tst/_search',
    'TSE': '/api_publica_tse/_search',
    'STJ': '/api_publica_stj/_search',
    'STM': '/api_publica_stm/_search',
}

ENDPOINTS_TRF = {
    'TRF1': '/api_publica_trf1/_search',
    'TRF2': '/api_publica_trf2/_search',
    'TRF3': '/api_publica_trf3/_search',
    'TRF4': '/api_publica_trf4/_search',
    'TRF5': '/api_publica_trf5/_search',
    'TRF6': '/api_publica_trf6/_search',
}

ENDPOINTS_EST = {
    'AC': '/api_publica_tjac/_search',
    'AL': '/api_publica_tjal/_search',
    'AM': '/api_publica_tjam/_search',
    'AP': '/api_publica_tjap/_search',
    'BA': '/api_publica_tjba/_search',
    'CE': '/api_publica_tjce/_search',
    'DF': '/api_publica_tjdft/_search',
    'ES': '/api_publica_tjes/_search',
    'GO': '/api_publica_tjgo/_search',
    'MA': '/api_publica_tjma/_search',
    'MG': '/api_publica_tjmg/_search',
    'MS': '/api_publica_tjms/_search',
    'MT': '/api_publica_tjmt/_search',
    'PA': '/api_publica_tjpa/_search',
    'PB': '/api_publica_tjpb/_search',
    'PE': '/api_publica_tjpe/_search',
    'PI': '/api_publica_tjpi/_search',
    'PR': '/api_publica_tjpr/_search',
    'RJ': '/api_publica_tjrj/_search',
    'RN': '/api_publica_tjrn/_search',
    'RO': '/api_publica_tjro/_search',
    'RR': '/api_publica_tjrr/_search',
    'RS': '/api_publica_tjrs/_search',
    'SC': '/api_publica_tjsc/_search',
    'SE': '/api_publica_tjse/_search',
    'SP': '/api_publica_tjsp/_search',
    'TO': '/api_publica_tjto/_search',
}

ENDPOINTS_TRT = {
    'TRT1': '/api_publica_trt1/_search',
    'TRT2': '/api_publica_trt2/_search',
    'TRT3': '/api_publica_trt3/_search',
    'TRT4': '/api_publica_trt4/_search',
    'TRT5': '/api_publica_trt5/_search',
    'TRT6': '/api_publica_trt6/_search',
    'TRT7': '/api_publica_trt7/_search',
    'TRT8': '/api_publica_trt8/_search',
    'TRT9': '/api_publica_trt9/_search',
    'TRT10': '/api_publica_trt10/_search',
    'TRT11': '/api_publica_trt11/_search',
    'TRT12': '/api_publica_trt12/_search',
    'TRT13': '/api_publica_trt13/_search',
    'TRT14': '/api_publica_trt14/_search',
    'TRT15': '/api_publica_trt15/_search',
    'TRT16': '/api_publica_trt16/_search',
    'TRT17': '/api_publica_trt17/_search',
    'TRT18': '/api_publica_trt18/_search',
    'TRT19': '/api_publica_trt19/_search',
    'TRT20': '/api_publica_trt20/_search',
    'TRT21': '/api_publica_trt21/_search',
    'TRT22': '/api_publica_trt22/_search',
    'TRT23': '/api_publica_trt23/_search',
    'TRT24': '/api_publica_trt24/_search',
}

ENDPOINTS_TRE = {
    'TRE-AC': '/api_publica_tre-ac/_search',
    'TRE-AL': '/api_publica_tre-al/_search',
    'TRE-AM': '/api_publica_tre-am/_search',
    'TRE-AP': '/api_publica_tre-ap/_search',
    'TRE-BA': '/api_publica_tre-ba/_search',
    'TRE-CE': '/api_publica_tre-ce/_search',
    'TRE-DF': '/api_publica_tre-dft/_search',
    'TRE-ES': '/api_publica_tre-es/_search',
    'TRE-GO': '/api_publica_tre-go/_search',
    'TRE-MA': '/api_publica_tre-ma/_search',
    'TRE-MG': '/api_publica_tre-mg/_search',
    'TRE-MS': '/api_publica_tre-ms/_search',
    'TRE-MT': '/api_publica_tre-mt/_search',
    'TRE-PA': '/api_publica_tre-pa/_search',
    'TRE-PB': '/api_publica_tre-pb/_search',
    'TRE-PE': '/api_publica_tre-pe/_search',
    'TRE-PI': '/api_publica_tre-pi/_search',
    'TRE-PR': '/api_publica_tre-pr/_search',
    'TRE-RJ': '/api_publica_tre-rj/_search',
    'TRE-RN': '/api_publica_tre-rn/_search',
    'TRE-RO': '/api_publica_tre-ro/_search',
    'TRE-RR': '/api_publica_tre-rr/_search',
    'TRE-RS': '/api_publica_tre-rs/_search',
    'TRE-SC': '/api_publica_tre-sc/_search',
    'TRE-SE': '/api_publica_tre-se/_search',
    'TRE-SP': '/api_publica_tre-sp/_search',
    'TRE-TO': '/api_publica_tre-to/_search',
}

ENDPOINTS_TJM = {
    'TJMMG': '/api_publica_tjmmg/_search',
    'TJMRS': '/api_publica_tjmrs/_search',
    'TJMSP': '/api_publica_tjmsp/_search',
}